import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/layout/Navbar";
import { ThemeProvider } from "next-themes";

const poppins = Poppins({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ['400','700']
});

export const metadata: Metadata = {
  title: "Web Dev Blog",
  description: "Generated by create next app",
  icons: {icon:'/logo.svg'}
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn('antialiased flex flex-col min-h-screen px-2', poppins.variable)}
      >
        <ThemeProvider attribute='class' defaultTheme="system" enableSystem disableTransitionOnChange>
          <Navbar/>
          <main className="flex-grow">
            {children}
          </main>
          <footer>Footer</footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
